version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
            VITE_TEST: $$VITE_TEST
    volumes: 
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173
volumes:
  node_modules: