version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes: 
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 5173:5173
volumes:
  node_modules: